baseURL = 'https://cpsiff.github.io/'
languageCode = 'en-us'
title = 'Carter Sifferman'
publishdir = "cpsiff.github.io"
theme = "personal-hugo-theme"

[params]
    colortheme = "white"

[[params.social]]
    name = "github"
    link = "https://github.com/cpsiff"

[[menu.main]]
name = "Research"
url = "/research"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2